# Generated by Django 5.2.4 on 2025-07-07 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="이름"),
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sido", models.CharField(max_length=20, verbose_name="광역시도")),
                ("sigungu", models.CharField(max_length=20, verbose_name="시군구")),
                (
                    "eupmyeondong",
                    models.CharField(max_length=20, verbose_name="읍면동"),
                ),
            ],
            options={
                "verbose_name": "지역",
                "verbose_name_plural": "지역",
                "unique_together": {("sido", "sigungu", "eupmyeondong")},
            },
        ),
        migrations.AddField(
            model_name="restaurant",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="restaurants",
                to="restaurant.region",
                verbose_name="지역",
            ),
        ),
    ]
