name: Django CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.3]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # ✅ mysqlclient 설치에 필요한 시스템 패키지 먼저 설치
    - name: Install system dependencies for mysqlclient
      run: sudo apt-get install -y default-libmysqlclient-dev

    # ✅ pip 업그레이드 및 패키지 설치
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # ✅ 테스트 실행
    - name: Run Tests
      run: |
        python manage.py test
 
